# Generated by Django 2.2.6 on 2020-11-06 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_price', models.FloatField(blank=True, null=True)),
                ('maximum_price', models.FloatField(blank=True, null=True)),
                ('negotiable', models.BooleanField(default=False)),
                ('sample_of_product', models.ImageField(upload_to='adverts')),
                ('name_of_product', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('ending_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('PROCESSED_FOOD', 'PROCESSED_FOOD'), ('CROPS', 'CROPS'), ('FRUITS', 'FRUITS'), ('LIVESTOCK', 'LIVESTOCK'), ('STUDENT_ITEMS', 'STUDENT_ITEMS'), ('FARM_TOOLS', 'FARM_TOOLS'), ('FARM_MACHINERY', 'FARM_MACHINERY'), ('FARM_SERVICES', 'FARM_SERVICES'), ('FOOD_STUFF', 'FOOD_STUFF'), ('LAND', 'LAND'), ('OTHER', 'OTHER')], max_length=120)),
                ('view', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_image', to='ads.Ad')),
            ],
        ),
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('validity', models.CharField(max_length=10)),
                ('no_of_ads', models.IntegerField()),
                ('cost', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ad_categories')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ad Categories',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='ad_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_category', to='ads.AdCategory'),
        ),
        migrations.AddField(
            model_name='ad',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
        migrations.AddField(
            model_name='ad',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_ads', to='ads.Seller'),
        ),
    ]
