# Generated by Django 2.2.6 on 2020-11-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='fixed_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
