# Generated by Django 2.2.6 on 2020-11-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20201114_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prod_ad', to='products.Product'),
        ),
    ]
