# Generated by Django 2.2.6 on 2021-04-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20201114_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsoredad',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sponsoredad',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='maximum_price',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='minimum_price',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='name_of_product',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='sample_of_product',
        ),
        migrations.AlterField(
            model_name='ad',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_ad', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='AdImage',
        ),
        migrations.DeleteModel(
            name='SponsoredAd',
        ),
    ]
