# Generated by Django 2.2.6 on 2021-04-03 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_ad_exhausted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
