# Generated by Django 2.2.6 on 2021-04-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_ad_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='whatsapp_number',
            field=models.CharField(max_length=20),
        ),
    ]
