# Generated by Django 2.2.6 on 2021-04-11 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_auto_20210411_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ads.Ad')),
            ],
        ),
    ]
