# Generated by Django 2.2.6 on 2020-11-06 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('location_of_delivery', models.CharField(max_length=1000)),
                ('total_price', models.FloatField()),
                ('expected_delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='products')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('PROCESSED_FOOD', 'PROCESSED_FOOD'), ('CROPS', 'CROPS'), ('FRUITS', 'FRUITS'), ('LIVESTOCK', 'LIVESTOCK'), ('STUDENT_ITEMS', 'STUDENT_ITEMS'), ('FARM_TOOLS', 'FARM_TOOLS'), ('FARM_MACHINERY', 'FARM_MACHINERY'), ('FARM_SERVICES', 'FARM_SERVICES'), ('FOOD_STUFF', 'FOOD_STUFF'), ('LAND', 'LAND'), ('OTHER', 'OTHER')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('user', models.CharField(max_length=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_cart', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('im_reference_code', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=400, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('paystack_reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=200, null=True)),
                ('time_left', models.IntegerField(default=50)),
                ('pay_on_delivery', models.BooleanField(default=False)),
                ('order_items', models.ManyToManyField(to='products.OrderedProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
