# Generated by Django 2.2.6 on 2021-04-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210403_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ad_payment_settled',
            field=models.BooleanField(default=True),
        ),
    ]
